---
- name: Ansible Demo
  hosts: localhost
  become: true
  tasks:
     - name: Install Apache
       apt:
           name: apache2
           state: present
           update_cache: true

     - name: Create User
       user:
         name: devopsuser
         state: present

     - name: Start Apache
       service:
         name: apache2
         state: started
         enabled: true
